export const COLS = 20;
export const BASE_ANIM_DURATION = 1500;
export const BASE_ANIM_PAUSE = 10000;

export const TRANSLATE_SQUARES_DURATION = BASE_ANIM_DURATION / 10;
export const SCALE_STRIPES_DURATION = BASE_ANIM_DURATION;
export const SCALE_STRIPES_ITERATIONS = 12;
export const SCALE_STRIPES_TOTAL_DURATION =
  SCALE_STRIPES_ITERATIONS * SCALE_STRIPES_DURATION;
export const SWIPE_STRIPES_DURATION = BASE_ANIM_DURATION / 2;
export const SWIPE_STRIPES_TOTAL_DURATION = SWIPE_STRIPES_DURATION * (COLS / 4);
export const ANIM_CHAIN_SINGLE_DURATION = BASE_ANIM_DURATION;
export const ROTATE_LINES_DURATION = 500;
